version: "3.2"
services:
  db:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
